# Generated by Django 4.0.3 on 2022-08-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_alter_automobilevo_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
