# Generated by Django 4.0.3 on 2022-08-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_alter_serviceappointment_vin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilevo',
            name='VIN',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='VIN',
            field=models.CharField(max_length=30),
        ),
    ]
