# Generated by Django 4.0.3 on 2022-08-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_alter_automobilevo_vin_alter_serviceappointment_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceappointment',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
